services:
  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - /opt/data/services/rclone:/config
      - /mnt/rclone:/mnt/rclone:shared
      - ./scripts/setup-rclone.sh:/setup-rclone.sh
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    networks:
      - mediastack
    entrypoint: "/setup-rclone.sh"
  rdtclient:
    container_name: rdtclient
    image: rogerfar/rdtclient:latest
    env_file: .env
    volumes:
      - /opt/data/services/rdtclient:/data/db
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/setup-rdtclient.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    env_file: .env
    environment:
      - PORT=9696
      - API_VERSION=1
    volumes:
      - /opt/data/services/prowlarr:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-prowlarr.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    env_file: .env
    environment:
      - PORT=8989
      - API_VERSION=3
    volumes:
      - /opt/data/services/sonarr:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-sonarr.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  sonarr-anime:
    container_name: sonarr-anime
    image: lscr.io/linuxserver/sonarr:latest
    env_file: .env
    environment:
      - PORT=8989
      - API_VERSION=3
    volumes:
      - /opt/data/services/sonarr-anime:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-sonarr.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    env_file: .env
    environment:
      - PORT=7878
      - API_VERSION=3
    volumes:
      - /opt/data/services/radarr:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-radarr.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    env_file: .env
    environment:
      - PORT=8686
      - API_VERSION=1
    volumes:
      - /opt/data/services/lidarr:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-lidarr.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    env_file: .env
    environment:
      - PORT=6767
      - API_VERSION=3
    volumes:
      - /opt/data/services/bazarr:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-bazarr.sh:/custom-cont-init.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    environment:
      - PORT=8096
      - API_VERSION=1
    volumes:
      - /opt/data/services/jellyfin:/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
      - ./scripts/init-envs.sh:/custom-cont-init.d/init
      - ./scripts/setup-jellyfin.sh:/custom-services.d/setup
    networks:
      - mediastack
    restart: unless-stopped
  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    environment:
      - LOG_LEVEL=info
    env_file: .env
    volumes:
      - /opt/data/services/seerr:/app/config
      - /opt/data:/data
      - /mnt/rclone:/mnt/rclone:slave
    networks:
      - mediastack
    restart: unless-stopped
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    env_file: .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - mediastack
    restart: unless-stopped
networks:
  mediastack:
    driver: bridge